import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Font Configurations
 * Using Next.js Google Fonts optimization.
 * geistSans: Used for the main application text.
 * geistMono: Used for code blocks and monospace requirements.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Application Metadata
 * Defines the title and description for SEO and browser tabs.
 */
export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

/**
 * RootLayout Component
 * The primary wrapper for the entire application.
 * This component handles global state providers, global styling,
 * and the top-level navigation/header structure.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          ClerkProvider wraps the application to provide authentication
          context and hooks to all child components.
        */}
        <ClerkProvider>
          {/*
            Global Header:
            Contains authentication triggers. The visibility of buttons
            depends on the user's current authentication state.
          */}
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            {/* Rendered only when the user is not authenticated */}
            <Show when="signed-out">
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            {/* Rendered only when the user is authenticated */}
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          {/* Main content area where pages are rendered */}
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
